blank_issues_enabled: true
contact_links:
  - name: Onboarding
    url: https://github.com/tekcin/MrBeanBot/discussions
    about: New to MrBeanBot? Visit our Discussions for setup guidance.
  - name: Support
    url: https://github.com/tekcin/MrBeanBot/discussions
    about: Get help from the community in GitHub Discussions.
